#!/usr/bin/env python3
"""Measure the romanization effect the A4 memo depends on.

Claim under test: how does chat-style romanized Indic text price against native
script, per tokenizer generation? This changes how routing premiums apply to
real chat traffic (heavily romanized).

Method: transliterate each FLORES Indic file to Latin with a standard scheme
(IAST via indic-transliteration), then approximate chat-style romanization by
stripping diacritics (NFD, drop combining marks), lowercasing, normalizing
danda punctuation to periods, and mapping the candra vowels sanscript leaves
unmapped. Tokenize native vs romanized against the same English baseline.

Known artifacts of the scheme, stated up front (all visible in the output):
  - IAST retains schwas and uses c-for-ch, r-for-d in retroflex flaps, so e.g.
    "मुझे थोड़ा पानी चाहिए।" -> "mujhe thora pani cahie." (chat Hindi would
    write "mujhe thoda pani chahie") — clean-scheme numbers bound, not settle,
    organic chat spelling.
  - sanscript's TAMIL->IAST invents aspirated consonants Tamil orthography
    cannot express ("ibhbhodhu" for இப்போது, real Tanglish "ippodhu"). We
    therefore ALSO report a fully de-aspirated Tamil lower bound; real Tanglish
    (which keeps th/dh in places) sits between the two.
  - Residual source-script codepoints after transliteration are counted and
    reported per language, so the pipeline's coverage is measured, not assumed.
"""

import re
import sys
import unicodedata
from pathlib import Path

CHAT_SCHWA = re.compile(r"(?<=[bcdfghjklmnpqrstvwxyz])a\b")
CHAT_C = re.compile(r"c(?!h)")

import tiktoken
from indic_transliteration import sanscript

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "corpus" / "data"

SCHEMES = {
    "hin": sanscript.DEVANAGARI, "mar": sanscript.DEVANAGARI,
    "ben": sanscript.BENGALI, "kan": sanscript.KANNADA,
    "tam": sanscript.TAMIL, "tel": sanscript.TELUGU,
}
# candra vowels/signs sanscript leaves unmapped (common in English loanwords)
CANDRA = str.maketrans({"ऑ": "o", "ॉ": "o", "ऍ": "e", "ॅ": "e"})
DEASPIRATE = re.compile(r"([bdgjkt])h")  # full de-aspiration (lower bound)


def read(lang):
    lines = [l for l in (DATA / f"{lang}.txt").read_text(encoding="utf-8").split("\n") if l.strip()]
    return [unicodedata.normalize("NFC", l) for l in lines]


def chatify(text, scheme):
    """IAST -> strip diacritics -> lowercase; danda -> '.', candra -> o/e."""
    latin = sanscript.transliterate(text, scheme, sanscript.IAST)
    latin = latin.replace("॥", ".").replace("।", ".").replace("|", ".")
    latin = latin.translate(CANDRA)
    decomposed = unicodedata.normalize("NFD", latin)
    return "".join(c for c in decomposed if not unicodedata.combining(c)).lower()


def chat_conventions(s):
    """Attested Hinglish conventions on top of the scheme output (a probe:
    word-final schwa deletion, c->ch, v->w), to measure which way organic
    spelling moves the numbers relative to the clean scheme."""
    s = CHAT_SCHWA.sub("", s)
    s = CHAT_C.sub("ch", s)
    return s.replace("v", "w")


def residual_stats(lines):
    """Count non-ASCII letters surviving transliteration (coverage check)."""
    n_cp = sum(1 for l in lines for c in l if ord(c) > 0x7F and c.isalpha())
    n_lines = sum(1 for l in lines if any(ord(c) > 0x7F and c.isalpha() for c in l))
    return n_cp, n_lines


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    encs = {name: tiktoken.get_encoding(name).encode for name in ("gpt2", "o200k_base")}
    eng = read("eng")
    eng_tok = {name: sum(len(e(l)) for l in eng) for name, e in encs.items()}

    out = ["# Romanization effect (generated by romanization.py)\n",
           "Parity vs English on the same 1012 parallel sentences, native script vs",
           "chat-style romanization (IAST, diacritics stripped, lowercased, danda->'.',",
           "candra vowels mapped). residual = source-script letters surviving",
           "transliteration (codepoints / lines affected), a coverage check:\n",
           "| lang | gpt2 native | gpt2 romanized | o200k native | o200k romanized | residual |",
           "|---|---|---|---|---|---|"]
    sample = None
    tam_range = None
    for lang, scheme in SCHEMES.items():
        native = read(lang)
        roman = [chatify(l, scheme) for l in native]
        if lang == "hin" and sample is None:
            probe = chatify("मुझे थोड़ा पानी चाहिए।", scheme)
            sample = probe
        r_cp, r_lines = residual_stats(roman)
        row = [lang]
        for name, e in encs.items():
            nat = sum(len(e(l)) for l in native) / eng_tok[name]
            rom = sum(len(e(l)) for l in roman) / eng_tok[name]
            row += [f"**{nat:.2f}x**", f"**{rom:.2f}x**"]
        row.append(f"{r_cp} cp / {r_lines} lines")
        out.append("| " + " | ".join(row) + " |")
        if lang == "tam":
            deasp = [DEASPIRATE.sub(r"\1", l) for l in roman]
            tam_range = {name: (sum(len(e(l)) for l in deasp) / eng_tok[name])
                         for name, e in encs.items()}

    hin_roman = [chatify(l, SCHEMES["hin"]) for l in read("hin")]
    hin_conv = [chat_conventions(l) for l in hin_roman]
    conv = {name: (sum(len(e(l)) for l in hin_conv) / eng_tok[name])
            for name, e in encs.items()}
    out += ["",
            f"probe (docstring example, actual output): मुझे थोड़ा पानी चाहिए। -> `{sample}`",
            "",
            "**Tamil artifact bound**: sanscript invents aspirates Tamil script cannot",
            "express; fully de-aspirated lower bound: "
            f"gpt2 **{tam_range['gpt2']:.2f}x**, o200k **{tam_range['o200k_base']:.2f}x** "
            "(real Tanglish keeps some th/dh, so it lies between the bound and the table row).",
            "",
            "**Organic-spelling direction (hin probe)**: applying attested Hinglish",
            "conventions (word-final schwa deletion, c->ch, v->w) on top of the scheme:",
            f"gpt2 {conv['gpt2']:.2f}x, o200k {conv['o200k_base']:.2f}x — i.e. organic",
            "spelling is CHEAPER than the clean scheme, and hin o200k stays above its",
            "native 1.57x.",
            ""]
    text = "\n".join(out)
    (HERE / "romanization_output.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"[written to {HERE / 'romanization_output.md'}]")


if __name__ == "__main__":
    main()
